### ISSUE TITLE
[Support]: 

### ISSUE THREAD

**Issue by mvpdms** [sinamics/ztnet#176] opened 2023-10-20 03:25 UTC
### 📝 Describe the Problem You Are Having

When going to the login page initially or if you logout with a light theme then you can't see the custom branding messages because the font is in white. Also on the sign in button, you can't see the words "sign in" because they are in white font.

### 🔖 Version

3.11

### 💻 Operating System

Ubuntu

**Comment by sinamics** [comment] 2023-10-20 04:45
Duplicate of #170

**Closed as completed by sinamics** 2023-10-20 04:45 UTC
